# Your workflow name.
name: Deploy to Hugging Face Spaces

# Run workflow on every push to main branch.
on:
  push:
    branches: [ main ]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

      # Login to Hugging Face
      - name: Login to Hugging Face
        uses: huggingface/huggingface-cli@v1.4.1
        with:
          token: ${{ secrets.HF_AUTH_TOKEN }}

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t ml-web-app .  # Replace with your desired image name

      # Push Docker Image to Hugging Face Hub
      - name: Push Docker Image to Hugging Face Hub
        uses: docker/push-action@v3
        with:
          username: ${{ secrets.HF_USERNAME }}
          password: ${{ secrets.HF_AUTH_TOKEN }}
          registry: docker.pkg.huggingface.co
          repository: ramhemanth580/githubactions-deployment  # Replace with your username and desired repository name

      # Deploy Docker Image to Hugging Face Space
      - name: Deploy to Hugging Face Space
        run: |
          # Assuming your Space name is "your-space-name"
          huggingface hub artifact push docker://docker.pkg.huggingface.co/username/ml-web-app \
            --destination your-space-name